[tool.black]
line-length = 88
target-version = ['py310']
preview = true
enable-unstable-feature = ["string_processing"]

[tool.isort]
profile = "black"
line_length = 88
known_third_party = ["django"]
known_first_party = []
default_section = "THIRDPARTY"
force_sort_within_sections = true
combine_as_imports = true
