# Generated by Django 4.2.16 on 2025-08-25 12:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("chat_id", models.BigIntegerField()),
                ("welcome_message", models.TextField()),
                ("rules", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("supergroup", "supergroup"),
                            ("channel", "channel"),
                            ("group", "group"),
                        ],
                        default="group",
                        max_length=100,
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        choices=[("en", "English"), ("ru", "Russian")],
                        default="ru",
                        max_length=100,
                    ),
                ),
                ("stats_all", models.IntegerField(default=0)),
                ("stats_month", models.IntegerField(default=0)),
                ("stats_week", models.IntegerField(default=0)),
                ("stats_day", models.IntegerField(default=0)),
                ("is_short_info_enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="ChatMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nick", models.CharField(blank=True, max_length=30, null=True)),
                ("motto", models.CharField(blank=True, max_length=100, null=True)),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("is_tg_admin", models.BooleanField(default=False)),
                ("is_citizen", models.BooleanField(default=False)),
                ("role_title", models.CharField(max_length=100)),
                ("role_level", models.IntegerField(default=0)),
                ("stats_day", models.IntegerField(default=0)),
                ("stats_week", models.IntegerField(default=0)),
                ("stats_month", models.IntegerField(default=0)),
                ("stats_all", models.IntegerField(default=0)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("last_active", models.DateTimeField(auto_now=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="database.chat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Emojis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("key", models.CharField(max_length=255)),
                ("chat_id", models.BigIntegerField(blank=True, null=True)),
                ("symbol", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="RelationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("required_hp", models.IntegerField(default=100)),
                ("level", models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="SystemMessages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("chat_id", models.BigIntegerField(blank=True, null=True)),
                (
                    "lang",
                    models.CharField(
                        choices=[("en", "English"), ("ru", "Russian")],
                        default="ru",
                        max_length=2,
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("stats_day", models.IntegerField(default=0)),
                ("stats_week", models.IntegerField(default=0)),
                ("stats_month", models.IntegerField(default=0)),
                ("stats_all", models.IntegerField(default=0)),
                ("yoris_coin_balance", models.IntegerField(default=0)),
                ("chips_balance", models.IntegerField(default=0)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("yoris", "yoris coins"),
                            ("chips", "chips for casino"),
                        ],
                        default="yoris",
                        max_length=5,
                    ),
                ),
                (
                    "linked_chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.chat",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Warnings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reason", models.TextField()),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_warnings",
                        to="database.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="warnings",
                        to="database.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RPCommands",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rank",
                    models.CharField(
                        choices=[
                            ("🎗", "rank 1"),
                            ("🥉", "rank 2"),
                            ("🥈", "rank 3"),
                            ("🥇", "rank 4"),
                            ("🎖", "rank 5"),
                            ("🏅", "rank 6"),
                            ("🏆", "rank 7"),
                            ("🏵", "rank 8"),
                        ],
                        default="🎗",
                        max_length=2,
                    ),
                ),
                (
                    "by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_rewards",
                        to="database.user",
                    ),
                ),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rewards",
                        to="database.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Relation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_main", models.BooleanField(default=False)),
                ("hp", models.IntegerField(default=100)),
                (
                    "level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.relationlevel",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="database.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="database.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Credits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("return_date", models.DateField()),
                (
                    "lender_type",
                    models.CharField(
                        choices=[("system", "система"), ("user", "пользователь")],
                        default="system",
                        max_length=10,
                    ),
                ),
                ("principal", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "interest_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=5
                    ),
                ),
                (
                    "repaid",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=18
                    ),
                ),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("due_at", models.DateTimeField()),
                (
                    "lender_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="given_credits",
                        to="database.user",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="credits",
                        to="database.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("members", models.PositiveIntegerField(default=1)),
                (
                    "type",
                    models.CharField(
                        choices=[("opened", "opened"), ("closed", "closed")],
                        default="opened",
                        max_length=6,
                    ),
                ),
                (
                    "leader",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.chatmember",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Clan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("number", models.PositiveIntegerField()),
                (
                    "type",
                    models.CharField(
                        choices=[("opened", "opened"), ("closed", "closed")],
                        default="opened",
                        max_length=6,
                    ),
                ),
                ("members", models.PositiveIntegerField(default=1)),
                (
                    "leader",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lead_clan",
                        to="database.chatmember",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="chatmember",
            name="clan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.clan",
            ),
        ),
        migrations.AddField(
            model_name="chatmember",
            name="main_club",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.club",
            ),
        ),
        migrations.AddField(
            model_name="chatmember",
            name="spouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="database.user",
            ),
        ),
        migrations.AddField(
            model_name="chatmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="database.user",
            ),
        ),
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cooldown", models.DurationField(blank=True, null=True)),
                ("price", models.PositiveIntegerField(default=0)),
                (
                    "required_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actions",
                        to="database.relationlevel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("number", models.PositiveIntegerField()),
                ("text", models.TextField()),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "user", "number", "chat")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="chatmember",
            unique_together={("user", "chat")},
        ),
        migrations.CreateModel(
            name="BookMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("number", models.PositiveIntegerField()),
                ("message_id", models.PositiveIntegerField()),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.chat",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.user",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "user", "number", "chat")},
            },
        ),
    ]
