# Generated by Django 4.2.16 on 2025-09-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="chat_name",
            field=models.CharField(max_length=100),
        ),
    ]
