# Generated by Django 4.2.16 on 2025-09-21 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_alter_chat_chat_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="warn",
            name="warn_id",
        ),
    ]
