# Generated by Django 4.2.16 on 2025-08-27 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_prefix"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="stats_all",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="stats_day",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="stats_month",
        ),
        migrations.RemoveField(
            model_name="chat",
            name="stats_week",
        ),
        migrations.RemoveField(
            model_name="chatmember",
            name="stats_all",
        ),
        migrations.RemoveField(
            model_name="chatmember",
            name="stats_day",
        ),
        migrations.RemoveField(
            model_name="chatmember",
            name="stats_month",
        ),
        migrations.RemoveField(
            model_name="chatmember",
            name="stats_week",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stats_all",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stats_day",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stats_month",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stats_week",
        ),
        migrations.AddField(
            model_name="rpcommands",
            name="emoji",
            field=models.CharField(default=None, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rpcommands",
            name="text",
            field=models.CharField(default="some cool text", max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.chat",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.chatmember",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="database.user",
                    ),
                ),
            ],
        ),
    ]
