# Generated by Django 4.2.16 on 2025-09-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_remove_chat_stats_all_remove_chat_stats_day_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="chat",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="chatmember",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "состоит в чате"),
                    ("restricted", "состоит в чате с ограничениями"),
                    ("kicked", "удален с чата"),
                    ("banned", "заблокирован"),
                    ("left", "покинул чат"),
                ],
                default="active",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatmember",
            name="tg_admin_title",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_id",
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="chat",
            name="rules",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chat",
            name="welcome_message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
