# Generated by Django 4.2.16 on 2025-09-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_remove_warn_warn_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="trigger",
            name="contains_exactly_income",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trigger",
            name="contains_exactly_outcome",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trigger",
            name="contains_income",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trigger",
            name="contains_outcome",
            field=models.TextField(blank=True, null=True),
        ),
    ]
