# Generated by Django 4.2.16 on 2025-09-07 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_rename_name_user_first_name_chat_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="chat_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
