# Generated by Django 4.2.16 on 2025-09-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_remove_chat_chat_id_remove_user_user_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
