# Generated by Django 4.2.16 on 2025-09-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
