# Generated by Django 4.2.16 on 2025-09-08 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0007_alter_chat_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatmember",
            name="role_title",
        ),
    ]
