# Generated by Django 4.2.16 on 2025-09-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0008_remove_chatmember_role_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chat",
            name="name",
            field=models.CharField(db_column="name", max_length=100),
        ),
        migrations.RenameField(
            model_name="chat",
            old_name="name",
            new_name="chat_name",
        ),
    ]
