# Generated by Django 4.2.16 on 2025-09-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0009_alter_chat_name_rename_name_chat_chat_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="mute_period",
            field=models.IntegerField(default=60),
        ),
    ]
