# Generated by Django 4.2.16 on 2025-09-11 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0011_mute"),
    ]

    operations = [
        migrations.AddField(
            model_name="mute",
            name="tg_admin_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="mute",
            name="was_admin",
            field=models.BooleanField(default=False),
        ),
    ]
