# Generated by Django 4.2.16 on 2025-09-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0012_mute_tg_admin_title_mute_was_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="warn_period",
            field=models.IntegerField(default=10080),
        ),
    ]
