# Generated by Django 4.2.16 on 2025-09-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0014_warn_mute_reason_delete_warnings"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="warn_to_ban",
            field=models.IntegerField(default=3),
        ),
    ]
