# Generated by Django 4.2.16 on 2025-09-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0015_chat_warn_to_ban"),
    ]

    operations = [
        migrations.AddField(
            model_name="warn",
            name="warn_id",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
