# Generated by Django 4.2.16 on 2025-09-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0016_warn_warn_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chat",
            old_name="warn_to_ban",
            new_name="warn_limit",
        ),
    ]
